name: cepi-gameplay
main: me.cepi.gameplay.Main
version: 1.0.1
description: The gameplay core of Cepi
author: Cepi
api-version: 1.14
commands:
   afk:
      description: Makes you go afk!
      usage: /afk
   ely:
      description: Makes you fly!
      usage: /ely
      aliases: elytra
      permission: cepi.builder
   sc:
      description: Chat privately with other staff!
      usage: /sc [<message>]
      aliases: staffchat
      permission: cepi.staff
   list:
      description: Shows a list of all players
      usage: /list
   spawn:
      description: Sends a person to spawn
      usage: /spawn
      permission: cepi.builder
   setspawn:
      description: Sets the spawn
      usage: /setspawn
      permission: cepi.admin
   setspawn:
      description: Sets the spawn
      usage: /setspawn
      permission: cepi.admin
   discord:
      description: Shows the discord
      usage: /discord
   rename:
      description: Renames an item
      usage: /rename <...name>
   party:
      description: Manage a party!
      usage: /party <arguments>
   friends:
      description: Get some friends, or allow yourself to get friends!
      usage: /friends <arguments>
      aliases: friend
permissions:
   cepi.staff:
      description: Makes you oficially staff with basic staff perms on cepi.
      default: op
   cepi.builder:
      description: Basic permission for all builders
      default: op