name: cepi-gameplay
main: me.cepi.gameplay.Main
version: 1.0.1
description: The gameplay core of Cepi
author: Cepi
api-version: 1.15
commands:
   afk:
      description: Makes you go afk!
      usage: /afk
   ely:
      description: Makes you fly!
      usage: /ely
      aliases: elytra
      permission: cepi.builder
   sc:
      description: Chat privately with other staff!
      usage: /sc [<message>]
      aliases: staffchat
      permission: cepi.staff
   list:
      description: Shows a list of all players
      usage: /list
   spawn:
      description: Sends a person to spawn
      usage: /spawn
      permission: cepi.builder
   setspawn:
      description: Sets the spawn
      usage: /setspawn
      permission: cepi.admin
   setspawn:
      description: Sets the spawn
      usage: /setspawn
      permission: cepi.admin
   discord:
      description: Shows the discord
      usage: /discord
   rename:
      description: Renames an item
      usage: /rename <...name>
   party:
      description: Manage a party!
      usage: /party <arguments>
   friends:
      description: Get some friends, or allow yourself to get friends!
      usage: /friends <arguments>
      aliases: friend
   serverstatus:
      description: Get the server status
      usage: /serverstatus
      permission: cepi.debug
   eco:
      description: Manage the economy
      usage: /eco
      permission: cepi.eco
   bal:
      description: Check your balance
      usage: /bal
      aliases: balance
   gamemode:
      description: Manipulate your gamemode
      usage: /gamemode <gamemode>
      aliases: [gmc, gms, gmsp, gma]
   top:
      permission: cepi.builder
      description: Teleports you to the top
      usage: /top
   speed:
      permission: cepi.builder
      description: Sets your speed
      usage: /speed <fly/walk> <speed>
      aliases: [flyspeed, walkspeed]
   skull:
      permission: cepi.builder
      description: Give the user a skull
      usage: /skull <player>
   fly:
      permission: cepi.builder
      description: Change the flight status of a player
      usage: /fly
   nv:
      permission: cepi.builder
      description: Activates or deactivates night vision
      usage: /nv
      aliases: [nightvision]
   warp:
      permission: cepi.builder
      description: Teleport to a warp
      usage: /warp <warp>
   warps:
      permission: cepi.builder
      description: See all warps
      usage: /warps
   setwarp:
      permission: cepi.builder
      description: Set a warp
      usage: /setwarp <warp>
   delwarp:
      permission: cepi.builder
      description: Delete a warp
      usage: /delwarp <warp>
      aliases: [deletewarp]
   buildworld:
      permission: cepi.builder
      description: Sends you to build world.
      usage: /buildworld
   kick:
      permission: cepi.mod
      usage: /kick <player> [<reason>]
      description: Kickes a player for a reason.
   tp:
      permission: cepi.staff
      usage: /tp <player>
      description: Teleport to a player.
   tphere:
      permission: cepi.staff
      usage: /tphere <player>
      description: Teleport a player to yourself.
   msg:
      usage: /msg <player>
      description: message a player.
   r:
      usage: /r <player>
      description: reply to the last player that messaged you.
   ban:
      usage: /ban <player>
      description: Ban a player.
   back:
      permission: cepi.staff
      usage: /back
      description: Teleports you to a previous location.
   shop:
      description: Manage shops
      permission: cepi.eco
      usage: /adminshop 
   sit:
      description: Sit
      permission: cepi.staff
      usage: /sit
   spawnmob:
      description: Spawn a mob
      permission: cepi.staff
      usage: /spawnmob <mob file>
   giveitem:
      description: Give an item
      permission: cepi.staff
      usage: /giveitem <item file>
permissions:
   cepi.mod:
      description: Basic permissions for cepi mods.
   cepi.staff:
      description: Makes you oficially staff with basic staff perms on cepi.
      default: op
   cepi.builder:
      description: Basic permission for all builders
      default: op
   cepi.eco:
      description: Basic permission for economy
      default: op
   cepi.debug:
      description: Basic permission for debugging
      default: op
   cepi.gamemode:
      description: Basic permission for gamemode manipulation
      default: op