name: cepi-gameplay
main: me.cepi.gameplay.Main
version: 1.0.1
description: The gameplay core of Cepi
author: Cepi
api-version: 1.14
commands:
   afk:
      description: Makes you go afk!
      usage: /afk
   ely:
      description: Makes you fly!
      usage: /ely
      aliases: elytra
   sc:
      description: Chat privately with other staff!
      usage: /sc [<message>]
      aliases: staffchat
permissions:
   cepi.staff:
      description: Makes you oficially staff with basic staff perms on cepi.
      default: op
   cepi.builder:
      description: Basic permission for all builders
      default: op