name: cepi-gameplay
main: me.cepi.gameplay.Main
version: 1.0.1
description: The gameplay core of Cepi
author: Cepi
api-version: 1.15
commands:
   afk:
      description: Makes you go afk!
      usage: /afk
   ely:
      description: Makes you fly!
      usage: /ely
      aliases: elytra
      permission: cepi.builder
   sc:
      description: Chat privately with other staff!
      usage: /sc [<message>]
      aliases: staffchat
      permission: cepi.staff
   list:
      description: Shows a list of all players
      usage: /list
   spawn:
      description: Sends a person to spawn
      usage: /spawn
      permission: cepi.builder
   setspawn:
      description: Sets the spawn
      usage: /setspawn
      permission: cepi.admin
   setspawn:
      description: Sets the spawn
      usage: /setspawn
      permission: cepi.admin
   discord:
      description: Shows the discord
      usage: /discord
   rename:
      description: Renames an item
      usage: /rename <...name>
   party:
      description: Manage a party!
      usage: /party <arguments>
   friends:
      description: Get some friends, or allow yourself to get friends!
      usage: /friends <arguments>
      aliases: friend
   serverstatus:
      description: Get the server status
      usage: /serverstatus
      permission: cepi.debug
   eco:
      description: Manage the economy
      usage: /eco
      permission: cepi.eco
   bal:
      description: Check your balance
      usage: /bal
      aliases: balance
   gamemode:
      description: Manipulate your gamemode
      usage: /gamemode <gamemode>
      aliases: [gmc, gms, gmsp, gma]
   top:
      permission: cepi.builder
      description: Teleports you to the top
      usage: /top
   speed:
      permission: cepi.builder
      description: Sets your speed
      usage: /speed <fly/walk> <speed>
      aliases: [flyspeed, walkspeed]
   skull:
      permission: cepi.builder
      description: Give the user a skull
      usage: /skull <player>
   fly:
      permission: cepi.builder
      description: Change the flight status of a player
      usage: /fly
permissions:
   cepi.staff:
      description: Makes you oficially staff with basic staff perms on cepi.
      default: op
   cepi.builder:
      description: Basic permission for all builders
      default: op
   cepi.eco:
      description: Basic permission for economy
      default: op
   cepi.debug:
      description: Basic permission for debugging
      default: op
   cepi.gamemode:
      description: Basic permission for gamemode manipulation
      default: op